In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('C:/Users/N Sree Haritha/Downloads/Forest_fire.csv')

In [3]:
df

         Area  Oxygen  Temperature  Humidity  Fire Occurrence
0    Jharkand      40           45        20                1
1   Bangalore      50           30        10                1
2     Ecuador      10           20        70                0
3           a      60           45        70                1
4   Bangalore      30           48        10                1
5           c      50           15        30                0
6          de       5           35        35                0
7         asd       5           20        70                0
8     Ecuador      60           32        19                1
9           r      30           50        45                1
10          t      40           55        80                1
11          y      30           39       100                0
12   Jharkand      10           12        12                0
13  Bangalore      20           23        23                0
14    Ecuador      60           34        15                1
15     canada      80            4        68                0
16          c      25           56        79                1
17          c      12           45        90                0
18        asd      28           43        15                1
19        asd      26            0        32                0
20         ad      32           37        21                1
21       sasd      45           48        12                1
22        asd      56           15        65                0
23      asdas      67           45        33                1
24        das      78           49         8                1
25        das      89           45        18                1
26        ads      21           12        44                0
27        ads      11           20        59                0
28        asd       1           32        70                0
29        NaN       5           20        45                0
30        NaN      42           43        20                1
31        NaN      32           60        30                1
32        NaN       5           15         5                0
33        NaN      20           30         5                0
34        NaN      30           51         2                1
35        NaN      60           60        10                1
36        NaN      10           10        60                0
37        NaN       0           30         0                0
38        NaN      45           45        15                1

In [4]:
df.isnull().sum()

Area               10
Oxygen              0
Temperature         0
Humidity            0
Fire Occurrence     0
dtype: int64

In [5]:
df= df.fillna(method='ffill')

In [6]:
df

         Area  Oxygen  Temperature  Humidity  Fire Occurrence
0    Jharkand      40           45        20                1
1   Bangalore      50           30        10                1
2     Ecuador      10           20        70                0
3           a      60           45        70                1
4   Bangalore      30           48        10                1
5           c      50           15        30                0
6          de       5           35        35                0
7         asd       5           20        70                0
8     Ecuador      60           32        19                1
9           r      30           50        45                1
10          t      40           55        80                1
11          y      30           39       100                0
12   Jharkand      10           12        12                0
13  Bangalore      20           23        23                0
14    Ecuador      60           34        15                1
15     canada      80            4        68                0
16          c      25           56        79                1
17          c      12           45        90                0
18        asd      28           43        15                1
19        asd      26            0        32                0
20         ad      32           37        21                1
21       sasd      45           48        12                1
22        asd      56           15        65                0
23      asdas      67           45        33                1
24        das      78           49         8                1
25        das      89           45        18                1
26        ads      21           12        44                0
27        ads      11           20        59                0
28        asd       1           32        70                0
29        asd       5           20        45                0
30        asd      42           43        20                1
31        asd      32           60        30                1
32        asd       5           15         5                0
33        asd      20           30         5                0
34        asd      30           51         2                1
35        asd      60           60        10                1
36        asd      10           10        60                0
37        asd       0           30         0                0
38        asd      45           45        15                1

In [7]:
df = pd.get_dummies(df, drop_first=True)

In [8]:
df

,Oxygen,Temperature,Humidity,Fire Occurrence,Area_Ecuador,Area_Jharkand,Area_a,Area_ad,Area_ads,Area_asd,Area_asdas,Area_c,Area_canada,Area_das,Area_de,Area_r,Area_sasd,Area_t,Area_y
0,40,45,20,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,50,30,10,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,10,20,70,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,60,45,70,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
4,30,48,10,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,50,15,30,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
6,5,35,35,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
7,5,20,70,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
8,60,32,19,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,30,50,45,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
10,40,55,80,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
11,30,39,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
12,10,12,12,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
13,20,23,23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,60,34,15,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
15,80,4,68,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
16,25,56,79,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
17,12,45,90,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
18,28,43,15,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
19,26,0,32,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
20,32,37,21,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
21,45,48,12,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
22,56,15,65,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
23,67,45,33,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
24,78,49,8,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
25,89,45,18,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
26,21,12,44,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
27,11,20,59,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
28,1,32,70,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
29,5,20,45,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
30,42,43,20,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
31,32,60,30,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
32,5,15,5,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
33,20,30,5,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
34,30,51,2,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
35,60,60,10,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
36,10,10,60,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
37,0,30,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
38,45,45,15,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
import joblib

In [10]:
x=df.drop('Fire Occurrence',axis=1)
y=df['Fire Occurrence']

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [12]:
rf = RandomForestClassifier(n_estimators = 100, random_state=42)

In [13]:
rf.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

In [14]:
y_pred = rf.predict(x_test)

In [15]:
accuracy_score(y_test,y_pred)

1.0

In [16]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00         2

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8

In [17]:
print(confusion_matrix(y_pred,y_test))

[[6 0]
 [0 2]]

In [18]:
joblib.dump(rf, 'random_forest_model.pkl')
print("Model saved successfully.")

Model saved successfully.

In [19]:
loaded_model = joblib.load('random_forest_model.pkl')
print(f'Type of loaded model: {type(loaded_model)}')

Type of loaded model: <class 'sklearn.ensemble._forest.RandomForestClassifier'>

In [20]:
sample_data = x_test.iloc[0].values.reshape(1, -1)
prediction =loaded_model.predict(sample_data)
print(f"Prediction: {prediction}")

Prediction: [0]

C:\Users\N SREE HARITHA\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [21]:
x_test

,Oxygen,Temperature,Humidity,Area_Ecuador,Area_Jharkand,Area_a,Area_ad,Area_ads,Area_asd,Area_asdas,Area_c,Area_canada,Area_das,Area_de,Area_r,Area_sasd,Area_t,Area_y
33,20,30,5,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
36,10,10,60,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
4,30,48,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,20,23,23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
30,42,43,20,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
26,21,12,44,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
6,5,35,35,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
27,11,20,59,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [22]:
sample_data

array([[20, 30,  5,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,
         0,  0]], dtype=int64)